name: data-processor
type: "python:3.10"

dependencies:
    python:
        pip: true  # Ensure pip is installed
    override: |
        pip install --upgrade --no-cache-dir pip poetry
        poetry config virtualenvs.create false
        poetry install --no-root
        pip uninstall -y poetry virtualenv-clone virtualenv

mounts:
    "/data": "shared:data"

crons:
    process_data:
        spec: "0 * * * *"  # Runs every hour; adjust as needed
        cmd: "python /app/update_datasets.py"

resources:
    cpu: "1"
    memory: "1024"
    disk: "512"