name: data-processor
type: "python:3.10"

#dependencies:
#    python3:
#        pip3: true  # Ensure pip is installed

hooks:
    build: |
        pip3 install -r requirements.txt
#        pip3 install --upgrade --no-cache-dir pip poetry
#        poetry config virtualenvs.create false
#        poetry install --no-root
#        pip3 uninstall -y poetry virtualenv-clone virtualenv

disk: 1024

mounts:
    '../data':
        source: service
        service: files
        source_path: ""
    '../nltk-data':
        source: service
        service: nltk-data
        source_path: ""

crons:
    process_data:
        spec: "0 1 * * *"  # Runs every day at 1 am
        cmd: "python /app/update_datasets.py"