name: frontend
type: "python:3.10"

#dependencies:
#    python3:
#        pip3: true  # Ensure pip is installed

hooks:
    build: |
        pip3 install --upgrade --no-cache-dir pip poetry
        poetry config installer.max-workers 4
        poetry config virtualenvs.create false
        poetry install --no-root
        pip3 uninstall -y poetry virtualenv-clone virtualenv

disk: 1024

mounts:
  "/data": "shared:files"
#  "/nltk_data": "shared:nltk_data"

web:
    commands:
        start: streamlit run app.py --server.address 0.0.0.0