name: frontend
type: "python:3.10"

dependencies:
    python:
        pip3: true  # Ensure pip is installed

hooks:
    build: |
        pip3 install --upgrade --no-cache-dir pip poetry
        poetry config virtualenvs.create false
        poetry install --no-root
        pip3 uninstall -y poetry virtualenv-clone virtualenv

disk: 1024

mounts:
  "/data": "shared:files"
#  "/nltk_data": "shared:nltk_data"

web:
    commands:
        start: bash -c "streamlit run /app/app.py --server.address 0.0.0.0 --server.port $PORT"