name: frontend
type: "python:3.10"

#dependencies:
#    python3:
#        pip3: true  # Ensure pip is installed

hooks:
    build: |
        pip3 install --upgrade --no-cache-dir pip poetry
        poetry config installer.max-workers 4
        poetry config virtualenvs.create false
        poetry install --no-root
        pip3 uninstall -y poetry virtualenv-clone virtualenv
#        pip3 install -r requirements.txt

disk: 1024

mounts:
    '/data':
        source: service
        service: files
        source_path: ""
    '/nltk-data':
        source: service
        service: nltk-data
        source_path: ""
web:
    commands:
        start: |
          streamlit run /app/app.py \
          --server.port $PORT \
          --server.enableWebsocketCompression false \
          --server.enableCORS false